# Site settings
title: thejang's Blog
image: img/home-bg.jpg
logo: img/favicon.png
email: thejang90@gmail.com
description: "Deeply Understanding Power System"
baseurl: ""
author: "Minseok Jang"
url: ""
#twitter_username: ""
github_username: theajang90
facebook_username: MSwindow
#gaid: ""
disqus_site_id: mswindow

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
safe: false # safe need to be off for local preview
lsi: false
permalink: pretty
paginate: 5
exclude: ["sass","node_modules","Gruntfile.js","package.json","README.md"]
keep_files: []
